### ISSUE TITLE
Ensemble in BlockChain

### ISSUE THREAD

**Issue by markpyzhov** [MallCloud/contracts-api#13]
The original text of requirements is described in [wiki/BlockChain-communication](https://github.com/MallCloud/contracts-api/wiki/BlockChain-communication#business-requirements).

> 2.  All transactions involving use of data, algorithms and ensembles whose state is set to "Publish" shall be registered on chain

So you think Ensemble usage will be something like this: 3 DS created 3 Predict Notebook for one RFS. 4th DS created Ensemble Notebook. 
We will manually configure Ensemble's author to be paid as 10% of RFS's royalty. 

Then if RFS's royalty will be $10000:
- Ensemble's author earns $1000
- DS 1 earns $5000
- DS 2 earns $1500
- DS 3 earns $2500

Is that correct?

**Comment by ehillerbrand** [comment]
Yes.  There will be DS who are experts at ensembling just like other DS are experts at algorithm development.
