### ISSUE TITLE
Analytic Object in the transaction and in RFS

### ISSUE THREAD

**Issue by markpyzhov** [MallCloud/contracts-api#14]
The original text of requirements is described in [wiki/BlockChain-communication](https://github.com/MallCloud/contracts-api/wiki/BlockChain-communication#business-requirements).

> 3.  Permission to access an Analytic Object can be granted on a single transaction basis or be granted for a specific RFS

Just to confirm as I understand the *"Analytic Object can be granted on a single transaction basis"*
means purchasing for Customer (or sharing or purchasing source code another DS).
Meanwhile *"an Analytic Object can be granted for a specific RFS"* means 
for Customer a getting result from AO (directly or further for an ensemble) without visibility of source code.

**Comment by ehillerbrand** [comment]
Let us suppose I have a dataset that I have loaded and I am a DS.

I may want the dataset to be used with Solution #A but not Solution #B.  How do I do that?

Or I may decide to sell the dataset on a recurring basis (for the next 6 months) or for a single use.  How do I do that?
