### ISSUE TITLE
Clarification of difference of an access to data OR to a sample data without access to the file

### ISSUE THREAD

**Issue by markpyzhov** [MallCloud/contracts-api#17]
The original text of requirements is described in [wiki/BlockChain-communication](https://github.com/MallCloud/contracts-api/wiki/BlockChain-communication#business-requirements).

> 5. Data use can occur through:
>     * ...
>     * Access to data via API in which the user cannot access the file (i.e., GraphQL)
>     * Access to a sample of data via API in which the user cannot access the file (i.e., GraphQL)

@ehillerbrand  can you explain how the first sub-item is difference from the second sub-item?

**Comment by ehillerbrand** [comment]
The only difference was is how the API provides access to the full data set or just a sample of the data.  @daemonslayer indicated that this would best be handled using a Rest API

**Comment by markpyzhov** [comment]
Closed since the proposal is covering that: https://github.com/MallCloud/Algorithm-Market-Platform/issues/74#issuecomment-338514603
