### ISSUE TITLE
Clarification of requirements for Canonical datasets or notebook in BlockChain

### ISSUE THREAD

**Issue by markpyzhov** [MallCloud/contracts-api#19]
The original text of requirements is described in [wiki/BlockChain-communication](https://github.com/MallCloud/contracts-api/wiki/BlockChain-communication#business-requirements).

> 6.  Canonical datasets or notebook templates associated with a solution are registered on chain

Can you explain how are "Canonical datasets or notebook" supposed to be used in BlockChain?

**Comment by ehillerbrand** [comment]
This is similar to the Dataset discussion.  I think it is easiest to say that everything is registered on blockchain.  So a Notebook associated with an RFS (a 'template') would be registered.  So too, a canonical dataset.  But maybe we have a $0 transaction or no transactions associated with the use.
