### ISSUE TITLE
Django API shares and purchase flows schemes confirmation

### ISSUE THREAD

**Issue by markpyzhov** [MallCloud/contracts-api#22]
## When the ensemble is executed then Administrator triggers Evaluation algorithm:
![evaluation_of_rfs](https://user-images.githubusercontent.com/4252051/32163807-16ab2c76-bd90-11e7-85a1-d79fd5a209de.png)

## Creation and publishing RFS:
![rfs_fixed_fee_access](https://user-images.githubusercontent.com/4252051/32163808-16cd3f1e-bd90-11e7-9649-d90437040222.png)

## Creation and publishing Analytic Object
![uploading_and_publishing_ao](https://user-images.githubusercontent.com/4252051/32164133-1d9f5628-bd91-11e7-860e-ede61b304a75.png)

## Purchase of source code:
![purchase_flow](https://user-images.githubusercontent.com/4252051/32163809-16eea1d6-bd90-11e7-8129-fb7c62635e0b.png)

## How User can download source code:
![downloading_source_code](https://user-images.githubusercontent.com/4252051/32163976-a7f83b7e-bd90-11e7-92c8-c9024dba0060.png)

## Sharing flows
![share_flows](https://user-images.githubusercontent.com/4252051/32164071-f0355250-bd90-11e7-9891-b24cfc5a7863.png)

**Comment by ehillerbrand** [comment]
These seem correct to me.

**Comment by kgupta15** [comment]
I just think that in `Creation and publishing Analytic Object`, RFS should have links to AO instead of AO linking itself to RFS. This will allow RFS to be a central contract and anybody will be able to verify all available resources (Notebooks, Dataset, DS, Collaborators) by using a single contract.

**Comment by markpyzhov** [comment]
> I just think that in `Creation and publishing Analytic Object`, RFS should have links to AO instead of AO linking itself to RFS. This will allow RFS to be a central contract and anybody will be able to verify all available resources (Notebooks, Dataset, DS, Collaborators) by using a single contract. 

Decided with @daemonslayer to keep both relations.

Closing since confirmed.
