### ISSUE TITLE
Rename 'API' into 'TrainedModel', 'GenerativeModel' or appropriative name

### ISSUE THREAD

**Issue by markpyzhov** [MallCloud/contracts-api#7]
Regarding the conversation: https://github.com/MallCloud/contracts-api/issues/6#issuecomment-324508630.

Especially in the docs: https://github.com/MallCloud/contracts-api/wiki/API-Access#create-api

**Comment by kgupta15** [comment]
@Teskuroi changed the name to TrainedModel
